USE [EEA_CAS_Enterprise]
GO

ALTER TABLE [dbo].[CaseViolation] ADD  CONSTRAINT [DF_CaseViolation_caseViolationId]  DEFAULT (newid()) FOR [caseViolationId]
GO

ALTER TABLE [CaseViolation]
ADD externalCaseViolationId NVARCHAR(100);


drop table if exists #tempPND;
	SELECT (SELECT [Date]
         , ENFDocumentNumber
    FROM
    (VALUES ( CONVERT(DATE, PRIOR_NON_DATE_1)
            , PRIOR_NON_DOC_NUM_1)
          , ( CONVERT(DATE, PRIOR_NON_DATE_2)
            , PRIOR_NON_DOC_NUM_2)
          , ( CONVERT(DATE, PRIOR_NON_DATE_3)
            , PRIOR_NON_DOC_NUM_3)) AS v([Date], ENFDocumentNumber)
    WHERE [Date] <> '1753-01-01T00:00:00'
    FOR JSON PATH) as priorNONDetails, cpv.PENCALC_VIOLATION_ID
	into #tempPND
FROM
src.cee_prod_PENCALC_VIOLATION             CPV
left JOIN      src.cee_prod_PENCALC         CPC ON CPC.PENCALC_ID = CPV.PENCALC_ID
--18538





INSERT INTO CaseViolation ( externalCaseViolationId,isDeleted, createdBy, createdDt, caseId
                          , citationId, fromDate, toDate, priorNONDetails, gravityDescription
                          , impactNumber, potentialImpactId, potentialImpactOther, potentialDamageId
                          , potentialDamageOther, previousNonCompliance, previousFailureToComplyId
                          , previousFailureToComplyOther, lackOfGoodFaithOrGoodFaithEffort, stepsToPreventId
                          , stepsToPreventOther, stepsToRTCId, stepsToRTCOther, remedyAndMitigateId
                          , remedyAndMitigateOther, financialConsideration, personAssessedId, personAssessedOther
                          , otherPersonAssessedId, otherPersonAssessedOther, financialConditionId, financialConditionOther
                          , publicInterest, publicInterestFactorId, publicInterestFactorOther, otherFactors
                          , otherFactorId, otherFactorOther, totalAdditionalRegulatoryFactors
                          , gravityTimesTotalAdditionalRegulatoryFactorsPlusGravity, maximumDailyPenaltyAllowedByStatute
                          , totalAdjustedPenaltyOrMaxDailyPenaltyIfSmaller, numberOfDaysOfViolation, comments
                          , economicBenefit, delayedId, delayedOther, avoidedId, avoidedOther, profitId, profitOther
                          , totalPenaltyPerViolation, totalCalculatedPenalty--, totalAmountDescription
						  , totalAmountClassification, totalAmountStartDate, totalAmountBasePenaltyTotal, totalAmountMaxPenaltyTotal
                          --, totalAmountGravityTotal, totalAmountAdditionalRegulatoryFactorsTotal
                          --, totalAmountAdjustedPenaltyOrMaxDailyPenaltyTotal, totalAmountAdjustedPenaltyXNumberOfDaysTotal
                          --, totalAmountMaxPenaltyXNumberOfDaysTotal, totalAmountCompMaxPenaltyXAdjustPenaltyTotal
                          , totalAmountEconomicBenefitTotal--, totalAmountCalculatedPenaltyTotal
						  )


SELECT distinct
  cpv.PENCALC_VIOLATION_ID as externalCaseViolationId
 ,0 as isDeleted
 , 'DataLoad' as createdBy
 , getdate() as createdDt
 , C.caseId as caseId
-- , CPC.PENCALC_SEARCH_KEY 
 , CTN.citationId as citationId
 --,ctn.citationNumber
 , CONVERT(DATE,VIOLATION_START_DATE) as fromDate                                             
 , CASE WHEN VIOLATION_END_DATE = '1753-01-01 00:00:00.000' THEN NULL ELSE CONVERT(DATE, VIOLATION_END_DATE) END   as toDate  
 , t.priorNONDetails AS priorNONDetails
 , VIOLATION_DESCRIPTION AS gravityDescription
--
 , GRAVITY * 100 AS impactNumber
 , CASE	WHEN GRAVITY_POTENTIAL_IMPACT = 'ACTUAL ENVIRONMENTAL IMPACT IDENTIFIED' then '536C6898-7F39-487F-BBE1-BF68C903DEDD'
		WHEN GRAVITY_POTENTIAL_IMPACT = 'ACTUAL PUBLIC HEALTH IMPACT IDENTIFIED' then '74422514-52DA-4E18-99E3-5F01F8408B35'
		WHEN GRAVITY_POTENTIAL_IMPACT = 'ACTUAL PUBLIC SAFETY AND WELFARE IMPACT IDENTIFIED' then '186E1F4E-41C6-4BB1-8DE2-1F17F34065D0'
		WHEN GRAVITY_POTENTIAL_IMPACT = 'POTENTIAL PUBLIC HEALTH IMPACT IDENTIFIED' then '6621536E-2924-4C09-9C37-A9F9AFE87409'
		WHEN GRAVITY_POTENTIAL_IMPACT = 'POTENTIAL ENVIRONMENTAL IMPACT IDENTIFIED' then 'B196E7A2-1D16-4239-96B6-4CF68E61EBFE'
		WHEN GRAVITY_POTENTIAL_IMPACT = 'POTENTIAL PUBLIC SAFETY AND WELFARE IMPACT IDENTIFIED' then '18288142-5341-4372-B7C4-89D8FE79BBE7'
      --  ELSE 'DB1D07A1-0C22-4806-891A-2FAD9491AA2E'
	END as potentialImpactId
 , case when GRAVITY_POTENTIAL_IMPACT not in ('ACTUAL ENVIRONMENTAL IMPACT IDENTIFIED','ACTUAL PUBLIC HEALTH IMPACT IDENTIFIED','ACTUAL PUBLIC SAFETY AND WELFARE IMPACT IDENTIFIED','POTENTIAL PUBLIC HEALTH IMPACT IDENTIFIED','POTENTIAL ENVIRONMENTAL IMPACT IDENTIFIED','POTENTIAL PUBLIC SAFETY AND WELFARE IMPACT IDENTIFIED') 
 then GRAVITY_POTENTIAL_IMPACT else null end as potentialImpactOther
 
 , CASE WHEN GRAVITY_POTENTIAL_DAMAGE = 'POTENTIAL COSTS/DAMAGES INCURRED BY THE COMMONWEALTH' THEN '4DCDEF49-D7CF-4BDF-A8A7-3F26638D90AF'
		WHEN GRAVITY_POTENTIAL_DAMAGE = 'POTENTIAL COSTS/DAMAGES INCURRED BY OTHERS' THEN '1E0B4365-2697-465B-AA33-B10078F6F6B8'
		WHEN GRAVITY_POTENTIAL_DAMAGE = 'ACTUAL COSTS/DAMAGES INCURRED BY THE COMMONWEALTH' THEN '7A720B2B-DC8C-4C40-95E2-77574F1BFE8A'
		WHEN GRAVITY_POTENTIAL_DAMAGE = 'ACTUAL COSTS/DAMAGES INCURRED BY OTHERS' THEN '888789E2-3C1E-4A83-85B4-0278608620C3'
		--ELSE '9ABF5447-646B-4699-B229-9FFC18606CF3'    
	END as potentialDamageId
 , case when GRAVITY_POTENTIAL_DAMAGE not in ('POTENTIAL COSTS/DAMAGES INCURRED BY THE COMMONWEALTH','POTENTIAL COSTS/DAMAGES INCURRED BY OTHERS','ACTUAL COSTS/DAMAGES INCURRED BY THE COMMONWEALTH','ACTUAL COSTS/DAMAGES INCURRED BY OTHERS') 
 then GRAVITY_POTENTIAL_DAMAGE else null end as potentialDamageOther
--  
 , HIST_OF_NON_COMPLIANCE * 100 as previousNonCompliance
 , CASE 
		WHEN HIST_OF_NON_COMPLIANCE_COMMENT = 'MORE THAN ONE VIOLATION AT THE SAME OR OTHER FACILITIES' THEN 'D49BBBD4-7511-4CAC-A2E1-36B3B5DCD1B0'
		WHEN HIST_OF_NON_COMPLIANCE_COMMENT = 'HIGHER-LEVEL ENFORCEMENT PENDING (OTHER PROGRAM(S)) (+ ONLY)' THEN '7918557C-F9CB-4074-B81D-43388F9C0FEE'		
		WHEN HIST_OF_NON_COMPLIANCE_COMMENT = 'LOWER-LEVEL ENFORCEMENT PENDING (OTHER PROGRAM(S)) (+ ONLY)' THEN 'CBD59E3F-1056-4494-9433-3FCABE08B6C4'		
		WHEN HIST_OF_NON_COMPLIANCE_COMMENT = 'LOWER-LEVEL ENFORCEMENT PREVIOUSLY ISSUED (+ ONLY)' THEN '9483ADBE-34F1-44B7-9585-70C3EEB33E07'		
		WHEN HIST_OF_NON_COMPLIANCE_COMMENT = 'SIMILAR/RECENT VIOLATIONS AT THE SAME OR OTHER FACILITIES' THEN '85362141-5991-4FCF-A1E1-D4F2F0097114'		
		WHEN HIST_OF_NON_COMPLIANCE_COMMENT = 'HIGHER-LEVEL ENFORCEMENT PREVIOUSLY ISSUED (+ ONLY)' THEN 'D9812DF5-C16D-4832-B676-27138B365425'		
		WHEN HIST_OF_NON_COMPLIANCE_COMMENT = 'OTHER ENFORCEMENT PENDING (AG, DA, EPA, LOCAL COMMUNITY, ETC.) (+ ONLY)' THEN 'FB1AE33D-4CE9-4EC8-82E8-58441B83D1A4'		
		--ELSE '389E3BF0-AFC5-4877-B414-7D159AC1879A'
  END as previousFailureToComplyId
 , case when HIST_OF_NON_COMPLIANCE_COMMENT not in ('MORE THAN ONE VIOLATION AT THE SAME OR OTHER FACILITIES','HIGHER-LEVEL ENFORCEMENT PENDING (OTHER PROGRAM(S)) (+ ONLY)','LOWER-LEVEL ENFORCEMENT PENDING (OTHER PROGRAM(S)) (+ ONLY)','LOWER-LEVEL ENFORCEMENT PREVIOUSLY ISSUED (+ ONLY)','SIMILAR/RECENT VIOLATIONS AT THE SAME OR OTHER FACILITIES','HIGHER-LEVEL ENFORCEMENT PREVIOUSLY ISSUED (+ ONLY)','OTHER ENFORCEMENT PENDING (AG, DA, EPA, LOCAL COMMUNITY, ETC.) (+ ONLY)') 
 then HIST_OF_NON_COMPLIANCE_COMMENT else null end as previousFailureToComplyOther
-- 
 , GOOD_FAITH * 100 as lackOfGoodFaithOrGoodFaithEffort
 , CASE 
		WHEN GOOD_FAITH_STEPS_PREVENT = 'VIOLATOR KNEW OF THE LEGAL REQUIREMENTS (+ ONLY)'  THEN '3C9D04B6-DBBF-4A33-A65C-9E495701D402'
 		WHEN GOOD_FAITH_STEPS_PREVENT = 'FAILURE TO EMPLOY BEST MANAGEMENT PRACTICES (+)'  THEN '1D6BE230-F0E8-4D0C-8372-982B29C744DA'
		WHEN GOOD_FAITH_STEPS_PREVENT = 'EMS - COMMITMENT TO DEVELOP AND IMPLEMENT (-)'  THEN 'BABA03C1-ACAC-4891-A383-013840F5AAE7'
		WHEN GOOD_FAITH_STEPS_PREVENT = 'VIOLATOR HAD/DID NOT HAVE CONTROL OVER THE VIOLATING EVENTS (+/-)'  THEN '909EF1C8-92DD-40C5-868B-63E7951AE639'
		WHEN GOOD_FAITH_STEPS_PREVENT = 'FAILURE TO COMPLY WITH EXISTING HLE-ACTION REQUIREMENTS (+)'  THEN 'F756DA66-0249-48FB-907C-DEE9EAC921B3'
		WHEN GOOD_FAITH_STEPS_PREVENT = 'FAILURE TO COMPLY WITH EXISTING PERMIT CONDITION(S) (+)'  THEN '4E274CA8-CE85-4330-AC37-504CD923982E'
		WHEN GOOD_FAITH_STEPS_PREVENT = 'FAILED TO COMPLY WITH CONDITIONS OF LOCAL ENFORCEMENT ACTION (+)'  THEN '8577EEC7-25C9-42A2-9913-0B00DDF0BFE0'
		WHEN GOOD_FAITH_STEPS_PREVENT = 'EMS - COMMITMENT NOT FULFILLED (+)'  THEN 'FCA621F4-75BE-43C1-A50E-9CA9183458CA'
		WHEN GOOD_FAITH_STEPS_PREVENT = 'FAILURE TO ADHERE TO APPROVED WORK PRACTICES (+)'  THEN '55149DAC-E82A-4F05-8D86-276CECF3A12F'
		--else  'A278AB2C-18FF-46D2-A3C4-BAA3BEA2135E'
END as stepsToPreventId
 ,case when GOOD_FAITH_STEPS_PREVENT not in ('VIOLATOR KNEW OF THE LEGAL REQUIREMENTS (+ ONLY)','FAILURE TO EMPLOY BEST MANAGEMENT PRACTICES (+)','EMS - COMMITMENT TO DEVELOP AND IMPLEMENT (-)','VIOLATOR HAD/DID NOT HAVE CONTROL OVER THE VIOLATING EVENTS (+/-)','FAILURE TO COMPLY WITH EXISTING HLE-ACTION REQUIREMENTS (+)','FAILURE TO COMPLY WITH EXISTING PERMIT CONDITION(S) (+)','FAILED TO COMPLY WITH CONDITIONS OF LOCAL ENFORCEMENT ACTION (+)','EMS - COMMITMENT NOT FULFILLED (+)','FAILURE TO ADHERE TO APPROVED WORK PRACTICES (+)') 
then GOOD_FAITH_STEPS_PREVENT else null end as stepsToPreventOther

 , CASE 
		WHEN GOOD_FAITH_STEPS_RTC ='IMPLEMENTED/FAILED TO CORRECT VIOLATION AT OR AFTER INSPECTION (-/+)' THEN 'DB1ECD11-1959-4560-AF99-9BA3EBEB7E33' 
		WHEN GOOD_FAITH_STEPS_RTC ='FAILED TO COMPLY WITH CONDITIONS OF LOCAL ENFORCEMENT ACTION (+)' THEN '8F979FC1-3B5E-421E-BA37-4A7720A78A92' 
		WHEN GOOD_FAITH_STEPS_RTC ='FAILURE TO COMPLY WITH EXISTING HLE-ACTION REQUIREMENTS (+)' THEN '3C1C972B-2949-40F2-B825-37411996DF86' 
		WHEN GOOD_FAITH_STEPS_RTC ='SUBMITTED/FAILED TO SUBMIT REQUESTED INFORMATION (-/+)' THEN '9009A691-C133-4202-8617-089BFD173746' 
		WHEN GOOD_FAITH_STEPS_RTC ='PERFORMED/FAILED TO PERFORM REQUIRED ACTION(S) (-/+)' THEN '2CF94CCD-6BB0-491E-8BA7-355D20EE50A2' 
		--else 'F903BD2C-FAC9-40F7-B757-B636E8EE58FD' 
 END as stepsToRTCId
 , case when GOOD_FAITH_STEPS_RTC not in ('IMPLEMENTED/FAILED TO CORRECT VIOLATION AT OR AFTER INSPECTION (-/+)','FAILED TO COMPLY WITH CONDITIONS OF LOCAL ENFORCEMENT ACTION (+)','FAILURE TO COMPLY WITH EXISTING HLE-ACTION REQUIREMENTS (+)','SUBMITTED/FAILED TO SUBMIT REQUESTED INFORMATION (-/+)','PERFORMED/FAILED TO PERFORM REQUIRED ACTION(S) (-/+)') 
 then GOOD_FAITH_STEPS_RTC else null end as stepsToRTCOther
 -- 
 , CASE WHEN GOOD_FAITH_REMEDY_MITIGATE = 'VIOLATOR''S RESPONSE WENT BEYOND THE EXPECTED STEPS TO REMEDY THE VIOLATION (-)'
        THEN '8932FBA6-D8A3-4E44-8D5F-3B9377EE91D0'
        WHEN GOOD_FAITH_REMEDY_MITIGATE = 'VIOLATOR''S RESPONSE WAS NOT TIMELY AND/OR ADEQUATE (+)'
        THEN '64ED815B-FE42-45B7-81D6-4F517C8C1941'
        WHEN GOOD_FAITH_REMEDY_MITIGATE = 'VIOLATOR HAD/DID NOT HAVE CONTROL OVER THE SPEED OF REMEDY (+/-)'
        THEN '2DE7DB93-53AD-4CF3-B1FB-3B1AAB825DF9'
        WHEN GOOD_FAITH_REMEDY_MITIGATE = 'CORRECTED/FAILED TO MITIGATE HARM AT OR AFTER AN INSPECTION (-/+)'
        THEN '736AFF2E-B57E-4531-8DDC-6D92C7CB637E'
        WHEN GOOD_FAITH_REMEDY_MITIGATE = 'RETAINED/FAILED TO RETAIN APPROPRIATE PROFESSIONAL (LSP, PE, SCIENTIST/SPECIALIST) (-/+)'
        THEN '8DC87D38-FD43-46FB-BC95-AB2102AE6D78'
		--else 'ED722CDF-404D-4837-B1AA-FD2EF1F61715'
END AS remedyAndMitigateId
 , case when GOOD_FAITH_REMEDY_MITIGATE not in ('VIOLATOR''S RESPONSE WENT BEYOND THE EXPECTED STEPS TO REMEDY THE VIOLATION (-)','VIOLATOR''S RESPONSE WAS NOT TIMELY AND/OR ADEQUATE (+)','VIOLATOR HAD/DID NOT HAVE CONTROL OVER THE SPEED OF REMEDY (+/-)','CORRECTED/FAILED TO MITIGATE HARM AT OR AFTER AN INSPECTION (-/+)','RETAINED/FAILED TO RETAIN APPROPRIATE PROFESSIONAL (LSP, PE, SCIENTIST/SPECIALIST) (-/+)') 
 then GOOD_FAITH_REMEDY_MITIGATE else null end as remedyAndMitigateOther
 , FINANCIAL_HARDSHIP * 100 as financialConsideration
 , CASE 
		WHEN FINANCIAL_HRDSHP_PEN_COMMENT ='DETER FUTURE VIOLATIONS AT THIS OR OTHER FACILITIES (+)' THEN '60714165-C8EC-4750-9D80-644938D2E0E2' 
		WHEN FINANCIAL_HRDSHP_PEN_COMMENT ='MAKE COMPLIANCE LESS COSTLY THAN NON-COMPLIANCE (+)' THEN '88B2C6CE-5C32-4989-BBCF-7E4A3595C725' 
		--else '215251A1-73D5-4A30-9751-567DED81448C' 
END as personAssessedId
 , case when FINANCIAL_HRDSHP_PEN_COMMENT not in ('DETER FUTURE VIOLATIONS AT THIS OR OTHER FACILITIES (+)','MAKE COMPLIANCE LESS COSTLY THAN NON-COMPLIANCE (+)') 
 then FINANCIAL_HRDSHP_PEN_COMMENT else null end as personAssessedOther

 , CASE 
		WHEN FINANCIAL_HRDSHP_PEN_OTHER_CMT = 'DETER FUTURE VIOLATIONS BY OTHERS IN SIMILAR INDUSTRY' THEN '5B14A48C-DBE9-48E9-80AC-632A384A9845' 
		WHEN FINANCIAL_HRDSHP_PEN_OTHER_CMT = 'DETER FUTURE VIOLATIONS BY OTHERS' THEN '5B447487-B886-4853-95AE-B803FB009BA5' 
		--else '7A6A9282-2074-4CA9-8311-04B4CBEA2F96' 
   END as otherPersonAssessedId
 , case when FINANCIAL_HRDSHP_PEN_OTHER_CMT not in ('DETER FUTURE VIOLATIONS BY OTHERS IN SIMILAR INDUSTRY','DETER FUTURE VIOLATIONS BY OTHERS') 
 then FINANCIAL_HRDSHP_PEN_OTHER_CMT else null end as otherPersonAssessedOther
 , CASE 
		WHEN FINANCIAL_HARDSHIP_CONDITIONS = 'ADJUSTMENT INTENDED TO PROMOTE A QUICKER RETURN TO COMPLIANCE (+)' THEN '1BF1B372-49BB-4966-9BF0-626423ED16FE'
		WHEN FINANCIAL_HARDSHIP_CONDITIONS = 'VIOLATOR PROVIDED SUFFICIENT INFORMATION TO SUBSTANTIATE AN "INABILITY TO PAY"' THEN 'CF261BF5-7C65-4F0D-A792-84C00E824802'
		WHEN FINANCIAL_HARDSHIP_CONDITIONS = 'PAYMENT OF A PENALTY WOULD IMPEDE THE ABILITY TO CONDUCT REMEDIAL MEASURES (-)' THEN '4113B5FE-3905-4E5C-9CB0-43B6D865D965'
		--ELSE 'E2BCB47A-73FA-4C18-BEBF-337E85C01311'
END as financialConditionId
 , case when FINANCIAL_HARDSHIP_CONDITIONS not in ('ADJUSTMENT INTENDED TO PROMOTE A QUICKER RETURN TO COMPLIANCE (+)','VIOLATOR PROVIDED SUFFICIENT INFORMATION TO SUBSTANTIATE AN "INABILITY TO PAY"','PAYMENT OF A PENALTY WOULD IMPEDE THE ABILITY TO CONDUCT REMEDIAL MEASURES (-)') 
 then FINANCIAL_HARDSHIP_CONDITIONS else null end as financialConditionOther
--select * from otherfactor
, PUBLIC_INTEREST * 100 as publicInterest
 , CASE WHEN PUBLIC_INTEREST_COMMENT = 'VIOLATION AFFECTS A MASSGIS MAPPED ENVIRONMENTAL JUSTICE (EJ) POPULATION (+)' THEN '9BF2EA15-89DC-4F9E-A8CE-F8C6085AF613'
		WHEN PUBLIC_INTEREST_COMMENT = 'PAYMENT OF A PENALTY WOULD THREATEN THE CONTINUED PROVISION OF AN ESSENTIAL SERVICE (-)' THEN '79C8CEBE-7485-4D61-8F03-9163915FC39C'
		WHEN PUBLIC_INTEREST_COMMENT = 'LITIGATION MIGHT IMPEDE THE DEPARTMENT''S ABILITY TO ENFORCE LAWS/REGULATIONS' THEN 'D64C4CC6-9A38-4EB9-887F-E99546447753'
		WHEN PUBLIC_INTEREST_COMMENT = 'PAYMENT OF A PENALTY COULD CAUSE VIOLATOR TO CHOOSE BETWEEN PAYING PENALTY OR REMEDIATION' THEN 'E11F1AD3-2C31-4F33-865B-04C5C1095309'
		--else 'D851F545-EF92-49ED-A912-4410D753F999'
 END as publicInterestId
 , CASE WHEN PUBLIC_INTEREST_COMMENT not in ('VIOLATION AFFECTS A MASSGIS MAPPED ENVIRONMENTAL JUSTICE (EJ) POPULATION (+)','PAYMENT OF A PENALTY WOULD THREATEN THE CONTINUED PROVISION OF AN ESSENTIAL SERVICE (-)','LITIGATION MIGHT IMPEDE THE DEPARTMENT''S ABILITY TO ENFORCE LAWS/REGULATIONS','PAYMENT OF A PENALTY COULD CAUSE VIOLATOR TO CHOOSE BETWEEN PAYING PENALTY OR REMEDIATION') 
 then PUBLIC_INTEREST_COMMENT else null end as publicInterestOther
 , OTHER_CIRCUMSTANCE * 100 as otherFactors
 , CASE WHEN OTHER_CIRCUMSTANCE_COMMENT = 'ACTUAL ENVIRONMENTAL IMPACT IDENTIFIED' THEN 'ED8A9A9E-6862-4104-97BE-80C897FF5386'
		WHEN OTHER_CIRCUMSTANCE_COMMENT = 'ACTUAL PUBLIC SAFETY AND WELFARE IMPACT IDENTIFIED' THEN '30515662-940A-47D5-BD9F-9798C21356A3'
		WHEN OTHER_CIRCUMSTANCE_COMMENT = 'POTENTIAL PUBLIC SAFETY AND WELFARE IMPACT IDENTIFIED' THEN '8EF5EEBF-F063-49DC-ABA2-E69EB6B1B8B1'
		WHEN OTHER_CIRCUMSTANCE_COMMENT = 'POTENTIAL PUBLIC HEALTH IMPACT IDENTIFIED' THEN '1EBE01C5-F17E-4710-908F-B9C95BD757EF'
		WHEN OTHER_CIRCUMSTANCE_COMMENT = 'ACTUAL PUBLIC HEALTH IMPACT IDENTIFIED' THEN '851836E0-9052-4981-AA3B-38EACFF74029'
		WHEN OTHER_CIRCUMSTANCE_COMMENT = 'POTENTIAL ENVIRONMENTAL IMPACT IDENTIFIED' THEN '45F19A0A-2295-4C08-9CE1-653710A02121'
		--else '391BC1D0-C92A-49CC-B6E9-D358D7143AEE'
 END as otherFactorId
 , CASE WHEN OTHER_CIRCUMSTANCE_COMMENT not in ('ACTUAL ENVIRONMENTAL IMPACT IDENTIFIED','ACTUAL PUBLIC SAFETY AND WELFARE IMPACT IDENTIFIED','POTENTIAL PUBLIC SAFETY AND WELFARE IMPACT IDENTIFIED','POTENTIAL PUBLIC HEALTH IMPACT IDENTIFIED','ACTUAL PUBLIC HEALTH IMPACT IDENTIFIED','POTENTIAL ENVIRONMENTAL IMPACT IDENTIFIED') 
 then OTHER_CIRCUMSTANCE_COMMENT else null end as otherFactorOther
--
 , SPECIAL_CIRCUMSTANCE_TOTAL * 100 as totalAdditionalRegulatoryFactors
 , BASE_X_GRAVITY_X_SPEC_CIRC as gravityTimesTotalAdditionalRegulatoryFactorsPlusGravity
 , MAX_DAILY_PENALTY  as maximumDailyPenaltyAllowedByStatute
 , CPV.ADJUSTED_PEN_COMP_STATE_MAX  as totalAdjustedPenaltyOrMaxDailyPenaltyIfSmaller
--
 , NUMBER_OF_DAYS  as numberOfDaysOfViolation
 , NUMBER_OF_DAYS_COMMENT as comments
 , ECONOMIC_BENEFIT as economicBenefit
 , CASE 
		WHEN ECONOMIC_BENEFIT_DELAYED ='POTENTIAL PUBLIC HEALTH IMPACT IDENTIFIED' THEN '040CA4C3-5F0D-4B17-8287-92972FE6BAA8'
		WHEN ECONOMIC_BENEFIT_DELAYED ='POTENTIAL ENVIRONMENTAL IMPACT IDENTIFIED' THEN 'CA091608-A620-4AED-BBF5-7CFA5A6D9B54'
		WHEN ECONOMIC_BENEFIT_DELAYED ='POTENTIAL PUBLIC SAFETY AND WELFARE IMPACT IDENTIFIED' THEN '377B165D-A241-4190-BF48-B5BD05D36ABB'
		WHEN ECONOMIC_BENEFIT_DELAYED ='ACTUAL PUBLIC SAFETY AND WELFARE IMPACT IDENTIFIED' THEN 'CBF187D1-448C-402A-BC5B-F4AD63907AF5'
		WHEN ECONOMIC_BENEFIT_DELAYED ='ACTUAL PUBLIC HEALTH IMPACT IDENTIFIED' THEN '86DFD4A9-F120-4A96-A50C-657AA7013F41'
		WHEN ECONOMIC_BENEFIT_DELAYED ='ACTUAL ENVIRONMENTAL IMPACT IDENTIFIED' THEN 'EF474C0E-AA6E-44C7-9ABD-D5931135F9FE'
		--else '174242CA-E1A0-40E6-8420-60A9CACE9129' 
 END as delayedId
 , case when ECONOMIC_BENEFIT_DELAYED not in ('POTENTIAL PUBLIC HEALTH IMPACT IDENTIFIED','POTENTIAL ENVIRONMENTAL IMPACT IDENTIFIED','POTENTIAL PUBLIC SAFETY AND WELFARE IMPACT IDENTIFIED','ACTUAL PUBLIC SAFETY AND WELFARE IMPACT IDENTIFIED','ACTUAL PUBLIC HEALTH IMPACT IDENTIFIED','ACTUAL ENVIRONMENTAL IMPACT IDENTIFIED')
 then ECONOMIC_BENEFIT_DELAYED else null end as delayedOther
 ,CASE 
       WHEN ECONOMIC_BENEFIT_AVOID = 'POTENTIAL PUBLIC HEALTH IMPACT IDENTIFIED' THEN '86EBA651-44A3-4D66-846C-2C628D99EC97'
       WHEN ECONOMIC_BENEFIT_AVOID = 'POTENTIAL PUBLIC SAFETY AND WELFARE IMPACT IDENTIFIED' THEN 'DFD8D813-81AB-41B1-BC26-52AC24E7E843'
       WHEN ECONOMIC_BENEFIT_AVOID = 'POTENTIAL ENVIRONMENTAL IMPACT IDENTIFIED' THEN '42595344-7926-4207-B3CE-1EAF0629A7F4'
       WHEN ECONOMIC_BENEFIT_AVOID = 'ACTUAL PUBLIC HEALTH IMPACT IDENTIFIED' THEN '6178E4D8-D1CD-4243-A24B-4239DD35FDD7'
       WHEN ECONOMIC_BENEFIT_AVOID = 'ACTUAL PUBLIC SAFETY AND WELFARE IMPACT IDENTIFIED' THEN 'ACB90AE7-9B20-42F7-9C91-6F6244EF28ED'
       WHEN ECONOMIC_BENEFIT_AVOID = 'ACTUAL ENVIRONMENTAL IMPACT IDENTIFIED' THEN '476736DE-4753-4255-9EAB-546BDD8FC5B2'
	   --else 'B2F2D466-23B5-4557-8C57-22DF7E8793E7'
 END as avoidedId
 
 ,case when ECONOMIC_BENEFIT_AVOID not in ('POTENTIAL PUBLIC HEALTH IMPACT IDENTIFIED','POTENTIAL PUBLIC SAFETY AND WELFARE IMPACT IDENTIFIED','POTENTIAL ENVIRONMENTAL IMPACT IDENTIFIED','ACTUAL PUBLIC HEALTH IMPACT IDENTIFIED','ACTUAL PUBLIC SAFETY AND WELFARE IMPACT IDENTIFIED','ACTUAL ENVIRONMENTAL IMPACT IDENTIFIED') 
 then ECONOMIC_BENEFIT_AVOID else null end as avoidedOther
-- select * from profit
 , CASE 
		WHEN ECONOMIC_BENEFIT_PROFITS = 'ACTUAL ENVIRONMENTAL IMPACT IDENTIFIED' THEN '97B690BB-8D9B-4184-B17A-780D75B19970'
		WHEN ECONOMIC_BENEFIT_PROFITS = 'POTENTIAL ENVIRONMENTAL IMPACT IDENTIFIED' THEN 'A4F7631E-0745-44F7-85FC-2B8B4ED4AAAC'
		WHEN ECONOMIC_BENEFIT_PROFITS = 'ACTUAL PUBLIC HEALTH IMPACT IDENTIFIED' THEN '0F31588C-8827-4F53-9D5B-CD553E6132DF'
		WHEN ECONOMIC_BENEFIT_PROFITS = 'POTENTIAL PUBLIC HEALTH IMPACT IDENTIFIED' THEN '30142998-4076-4FB9-AF2C-28099B0FC278'
		WHEN ECONOMIC_BENEFIT_PROFITS = 'POTENTIAL PUBLIC SAFETY AND WELFARE IMPACT IDENTIFIED' THEN '2421A023-DB00-4EA4-80AB-7C6C80D0D123'
		WHEN ECONOMIC_BENEFIT_PROFITS = 'ACTUAL PUBLIC SAFETY AND WELFARE IMPACT IDENTIFIED' THEN 'A4B15211-0D1B-47EB-9C91-C7772CA71176'
        --else 'D975735A-8D0E-477B-9C8C-660BDC307DA0'
 END as profitId
 , CASE WHEN ECONOMIC_BENEFIT_PROFITS not in ('ACTUAL ENVIRONMENTAL IMPACT IDENTIFIED','POTENTIAL ENVIRONMENTAL IMPACT IDENTIFIED','ACTUAL PUBLIC HEALTH IMPACT IDENTIFIED','POTENTIAL PUBLIC HEALTH IMPACT IDENTIFIED','POTENTIAL PUBLIC SAFETY AND WELFARE IMPACT IDENTIFIED','ACTUAL PUBLIC SAFETY AND WELFARE IMPACT IDENTIFIED') 
 THEN ECONOMIC_BENEFIT_PROFITS else null end as profitOther
--

 , ADJUSTED_PEN_X_NUM_DAYS as totalPenaltyPerViolation
 , CPV.CALCULATED_TOTAL as totalCalculatedPenalty
--
 , CCl.citationClassName as totalAmountClassification
 , CTN.startDate as totalAmountStartDate
--
 , BASE_PENALTY as totalAmountBasePenaltyTotal
 , BASE_PENALTY * NUMBER_OF_DAYS as totalAmountMaxPenaltyTotal
--  , totalAmountGravityTotal
--  , totalAmountAdditionalRegulatoryFactorsTotal
--  , totalAmountAdjustedPenaltyOrMaxDailyPenaltyTotal
--      , totalAmountNumberOfDaysTotal
--  , totalAmountAdjustedPenaltyXNumberOfDaysTotal
--  , totalAmountMaxPenaltyXNumberOfDaysTotal
--  , totalAmountCompMaxPenaltyXAdjustPenaltyTotal
--  , totalAmountEconomicBenefitTotal
--  , totalAmountCalculatedPenaltyTotal
-- , CONVERT(DECIMAL(11, 2), CALCULATED_AMOUNTS.GravityTotal)                                                                                                                                                      AS totalAmountGravityTotal
-- , CONVERT(DECIMAL(11, 2), CALCULATED_AMOUNTS.AdditionalRegulatoryFactorsTotal)                                                                                                                                  AS totalAmountAdditionalRegulatoryFactorsTotal
-- , CONVERT(DECIMAL(11, 2), CALCULATED_AMOUNTS.AdjustedPenaltyOrMaxDailyPenaltyTotal)                                                                                                                             AS totalAmountAdjustedPenaltyOrMaxDailyPenaltyTotal
-- , CONVERT(DECIMAL(11, 2), CPV.ADJUSTED_PEN_COMP_STATE_MAX * NUMBER_OF_DAYS)                                                                                                                                     AS totalAmountAdjustedPenaltyXNumberOfDaysTotal
-- , CONVERT(DECIMAL(11, 2), CPV.CALCULATED_TOTAL * NUMBER_OF_DAYS)                                                                                                                                                AS totalAmountMaxPenaltyXNumberOfDaysTotal
-- , CONVERT(DECIMAL(11, 2), CASE
--                           WHEN (CPV.ADJUSTED_PEN_COMP_STATE_MAX * NUMBER_OF_DAYS) < CPV.CALCULATED_TOTAL
--                           THEN CPV.ADJUSTED_PEN_COMP_STATE_MAX * NUMBER_OF_DAYS
--                           ELSE
--                           CPV.CALCULATED_TOTAL END)                                                                                                                                                     AS totalAmountCompMaxPenaltyXAdjustPenaltyTotal
-- , CONVERT(DECIMAL(11, 2), (CASE
--                           WHEN ((CCL.basePenaltyAmount * (1 + GRAVITY / 100)) + ((CCL.basePenaltyAmount * (1 + GRAVITY / 100)) * SPECIAL_CIRCUMSTANCE_TOTAL / 100)) > MAX_DAILY_PENALTY
--                            THEN MAX_DAILY_PENALTY
--                            ELSE
--                            (CCL.basePenaltyAmount * (1 + GRAVITY / 100)) + ((CCL.basePenaltyAmount * (1 + GRAVITY / 100)) * SPECIAL_CIRCUMSTANCE_TOTAL / 100) END) * NUMBER_OF_DAYS + ECONOMIC_BENEFIT) AS totalAmountCalculatedPenaltyTotal
-- , CONVERT(DECIMAL(11, 2), CALCULATED_AMOUNTS.AdjustedPenaltyOrMaxDailyPenaltyTotal * NUMBER_OF_DAYS + ECONOMIC_BENEFIT)                                                                                         AS totalAmountMaxPenaltyTotal
 , ECONOMIC_BENEFIT as totalAmountEconomicBenefitTotal

 --into #t
FROM
src.cee_prod_PENCALC_VIOLATION             cpv
left JOIN      src.cee_prod_PENCALC         cpc ON cpc.PENCALC_ID = cpv.PENCALC_ID
left join src_prod.CITATION ci on ci.CITATION_ID=cpv.CITATION_ID
left JOIN      [Citation]              ctn ON ctn.citationNumber = cpv.CITATION_ID
left join #tempPND t on t.PENCALC_VIOLATION_ID=cpv.PENCALC_VIOLATION_ID
left JOIN      [CitationClass]         ccl ON ccl.citationClassId = ctn.citationClassId
/* left JOIN      (SELECT CPV.PENCALC_VIOLATION_ID, GravityTotal, AdditionalRegulatoryFactorsTotal
                , CASE WHEN AdditionalRegulatoryFactorsTotal > MAX_DAILY_PENALTY THEN MAX_DAILY_PENALTY 
				ELSE AdditionalRegulatoryFactorsTotal END AS AdjustedPenaltyOrMaxDailyPenaltyTotal
           FROM
           src.cee_pencalc_violation CPV
           left JOIN src.cee_pencalc  CPC ON CPC.PENCALC_ID = CPV.PENCALC_ID
           left JOIN [Citation]       CTN ON CTN.citationNumber = CPV.CITATION_ACTIVITY_ID
           left JOIN [CitationClass]  CCL ON CCL.citationClassId = CTN.citationClassId
           left JOIN (SELECT CPV.PENCALC_VIOLATION_ID
                      , CALCULATED_GRAVITY_TOTAL.GravityTotal                                                                              AS GravityTotal
                      , CALCULATED_GRAVITY_TOTAL.GravityTotal + (CALCULATED_GRAVITY_TOTAL.GravityTotal * SPECIAL_CIRCUMSTANCE_TOTAL / 100) AS AdditionalRegulatoryFactorsTotal
                 FROM
                 src.cee_pencalc_violation cpv
                 left JOIN src.cee_pencalc  cpc ON cpc.PENCALC_ID = cpv.PENCALC_ID
                 left JOIN [Citation] ctn ON ctn.citationNumber = cpv.CITATION_ACTIVITY_ID
                 left JOIN [CitationClass] ccl ON ccl.citationClassId = ctn.citationClassId
                 left JOIN (SELECT cpv.PENCALC_VIOLATION_ID
                            , ccl.basePenaltyAmount * (1 + GRAVITY / 100) AS GravityTotal
                       FROM
                       src.cee_pencalc_violation CPV
                      left JOIN src.cee_pencalc  CPC ON CPC.PENCALC_ID = CPV.PENCALC_ID
                       left JOIN [Citation]       CTN ON CTN.citationNumber = CPV.CITATION_ACTIVITY_ID
                       left JOIN [CitationClass]  CCL ON CCL.citationClassId = CTN.citationClassId) AS CALCULATED_GRAVITY_TOTAL ON CALCULATED_GRAVITY_TOTAL.PENCALC_VIOLATION_ID = CPV.PENCALC_VIOLATION_ID)
                AS           CALCULATED_ADDITIONAL_REGULATORY_FACTORS_TOTAL ON CALCULATED_ADDITIONAL_REGULATORY_FACTORS_TOTAL.PENCALC_VIOLATION_ID = CPV.PENCALC_VIOLATION_ID)
          AS                  CALCULATED_AMOUNTS ON CALCULATED_AMOUNTS.PENCALC_VIOLATION_ID = CPV.PENCALC_VIOLATION_ID
*/
left JOIN      [Case]                  C ON  cast(cpc.PENCALC_ID as nvarchar(100))=c.externalCaseId--C.caseNumber = CPC.PENCALC_SEARCH_KEY
--LEFT JOIN [CitationClass]         CC ON CC.citationClassId = CTN.citationClassId
LEFT JOIN PotentialImpact         PI ON PI.potentialImpactName = CPV.GRAVITY_POTENTIAL_IMPACT
LEFT JOIN PotentialDamage         PD ON PD.potentialDamageName = CPV.GRAVITY_POTENTIAL_DAMAGE
LEFT JOIN PreviousFailureToComply PFC ON PFC.previousFailureToComplyName = CPV.HIST_OF_NON_COMPLIANCE_COMMENT
--
LEFT JOIN StepsToPrevent          STP ON STP.stepsToPreventName = CPV.GOOD_FAITH_STEPS_PREVENT
LEFT JOIN StepsToRTC              STR ON PFC.previousFailureToComplyName = CPV.GOOD_FAITH_STEPS_RTC
LEFT JOIN RemedyAndMitigate       RAM ON RAM.remedyAndMitigateName = CPV.GOOD_FAITH_REMEDY_MITIGATE
--
LEFT JOIN PersonAssessed          PA ON PA.personAssessedName = CPV.FINANCIAL_HRDSHP_PEN_COMMENT
LEFT JOIN OtherPersonAssessed     OPA ON OPA.otherPersonAssessedName = CPV.FINANCIAL_HRDSHP_PEN_OTHER_CMT
LEFT JOIN FinancialCondition      FC ON FC.financialConditionName = CPV.FINANCIAL_HARDSHIP_CONDITIONS
--
LEFT JOIN OtherFactor             [OF] ON [OF].otherFactorName = CPV.OTHER_CIRCUMSTANCE_COMMENT
--
LEFT JOIN Delayed                 D ON D.delayedName = CPV.ECONOMIC_BENEFIT_DELAYED
LEFT JOIN Avoided                 A ON A.avoidedName = CPV.ECONOMIC_BENEFIT_AVOID
LEFT JOIN Profit                  P ON P.profitName = CPV.ECONOMIC_BENEFIT_PROFITS
--where cpv.PENCALC_VIOLATION_ID=1
where cpv.PENCALC_ID is not null
order by 1
